[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"
     [plugins.inputs]
      # allowed values: electron, chromium
      browser = "electron"
      configFile = "cypress.config.ts"

      [plugins.inputs.preBuild]
      spec = "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}"
      enable = true
      start = 'yarn dev'
      wait-on = 'http://localhost:3000'
      wait-on-timeout = '30' # seconds