[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"
     [plugins.inputs]
      # allowed values: electron, chromium
      browser = "electron"
     

      [plugins.inputs.preBuild]
      # spec = "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}"
      configFile = "cypress.config.ts"
      enable = true
      start = 'yarn dev'
      wait-on = 'http://localhost:3000'
      wait-on-timeout = '30' # seconds