import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getAllBlogPosts } from "../libs/contentful";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ allPosts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tighter leading-tight md:leading-none mb-12 text-center md:text-left">
          {allPosts[0]?.title}
        </h1>
      </main>
    </>
  );
}

export async function getStaticProps({ preview = false }) {
  const allPosts = (await getAllBlogPosts(preview)) ?? [];
  return {
    props: { preview, allPosts },
  };
}
