import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import styles from "../styles/Home.module.css";
import { getAllBlogPosts } from "../libs/contentful";
import { Container } from "../libs/UI/Container";
import Intro from "../libs/UI/Intro";
import { HeroPost } from "../libs/UI/HeroPost";
import { MoreStories } from "../libs/UI/MoreStories";
import { Layout } from "../libs/UI/Layout";
import { IBlogPost } from "../libs/@types";

const inter = Inter({ subsets: ["latin"] });

interface IHomeProps {
  allPosts: IBlogPost[];
  preview: boolean;
}

export default function Home({ allPosts, preview }: IHomeProps) {
  const heroPost = allPosts[0];
  const morePosts = allPosts.slice(1);
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Container>
            <Intro />
            {heroPost && <HeroPost {...heroPost} />}
            {morePosts.length > 0 && <MoreStories posts={morePosts} />}
          </Container>
        </main>
      </Layout>
    </>
  );
}

export async function getStaticProps({ preview = false }) {
  const allPosts = (await getAllBlogPosts(preview)) ?? [];
  return {
    props: { preview, allPosts },
  };
}
